[project]
name = "fastapi-clerk-starter"
version = "0.1.0"
description = "A starter template for building secure and scalable FastAPI applications with Clerk authentication integration."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
